name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
      with:
        gradle-version: '8.9'
    - run: gradle build -x test
      
  generate-dependency-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
      with:
        gradle-version: '8.9'
    - name: Get dependencies with Gradle & run flatpak-gradle-generator plugin by jwharm
      run: gradle flatpakGradleGenerator
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update flatpak-sources.json"
        #branch: "dependency-file-update"
        #create_branch: true
        # Optional. Disable dirty check and always try to create a commit and push
        skip_dirty_check: true
        file_pattern: flatpak-sources.json

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
